"""Wide World Importers: schema-only inspection from the bacpac model.

SQL Server cannot run on this aarch64 host (no amd64 emulation), so table rows
remain UNINSPECTED. This module reads model.xml (DacFx schema), verifies its
checksum against Origin.xml, and extracts tables, columns, primary keys and
foreign keys. WWI rows are themselves generated by Microsoft's workload
simulator, so even inspected rows would not be empirical calibration.
"""

from __future__ import annotations

import hashlib
import sys
import zipfile
from collections import defaultdict

from lxml import etree

from wsb.lineage import ROOT, write_json

SID = "wide_world_importers"
UNZ = ROOT / "data" / "staged" / SID / "_unzip"
NS = {"d": "http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02"}
FOCUS = ("Purchasing", "Sales", "Warehouse")


def _name(el) -> str:
    return el.get("Name", "").replace("[", "").replace("]", "")


def extract_model() -> None:
    """Extract only model.xml and Origin.xml from the raw bacpac (a zip archive)."""
    UNZ.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(ROOT / "data" / "raw" / SID / "WideWorldImporters-Standard.bacpac") as zf:
        for name in ("model.xml", "Origin.xml"):
            if not (UNZ / name).exists():
                (UNZ / name).write_bytes(zf.read(name))


def parse() -> dict:
    extract_model()
    model = (UNZ / "model.xml").read_bytes()
    origin = etree.parse(str(UNZ / "Origin.xml"))
    expected = origin.findtext(".//d:Checksum[@Uri='/model.xml']", namespaces=NS)
    actual = hashlib.sha256(model).hexdigest().upper()
    root = etree.fromstring(model)
    tables: dict[str, dict] = {}
    for t in root.iterfind(".//d:Element[@Type='SqlTable']", NS):
        tname = _name(t)
        cols = []
        for c in t.iterfind("./d:Relationship[@Name='Columns']/d:Entry/d:Element", NS):
            ctype = c.find(".//d:Relationship[@Name='Type']/d:Entry/d:References", NS)
            nullable = c.find("./d:Property[@Name='IsNullable']", NS)
            cols.append({
                "name": _name(c).split(".")[-1],
                "kind": c.get("Type"),
                "type": ctype.get("Name").strip("[]") if ctype is not None else None,
                "nullable": nullable is None or nullable.get("Value") != "False",
            })
        tables[tname] = {"columns": cols, "pk": [], "fks": []}
    for pk in root.iterfind(".//d:Element[@Type='SqlPrimaryKeyConstraint']", NS):
        host = pk.find("./d:Relationship[@Name='DefiningTable']/d:Entry/d:References", NS)
        cols = [_name(r).split(".")[-1] for r in pk.iterfind(".//d:Relationship[@Name='ColumnSpecifications']//d:References", NS)]
        if host is not None and _name(host) in tables:
            tables[_name(host)]["pk"] = cols
    for fk in root.iterfind(".//d:Element[@Type='SqlForeignKeyConstraint']", NS):
        host = fk.find("./d:Relationship[@Name='DefiningTable']/d:Entry/d:References", NS)
        ref = fk.find("./d:Relationship[@Name='ForeignTable']/d:Entry/d:References", NS)
        cols = [_name(r).split(".")[-1] for r in fk.iterfind("./d:Relationship[@Name='Columns']/d:Entry/d:References", NS)]
        if host is not None and _name(host) in tables:
            tables[_name(host)]["fks"].append({"columns": cols, "references": _name(ref) if ref is not None else None})
    focus = {k: v for k, v in tables.items() if k.split(".")[0] in FOCUS and not k.endswith("_Archive")}
    by_schema = defaultdict(int)
    for k in tables:
        by_schema[k.split(".")[0]] += 1
    out = {
        "source_id": SID,
        "inspection_level": "schema only (model.xml); table rows NOT inspected",
        "model_checksum_matches_origin": expected == actual,
        "publisher_reported_total_rows": int(origin.findtext(".//d:TableRowCountTotalTag", namespaces=NS)),
        "tables_total": len(tables), "tables_by_schema": dict(by_schema),
        "focus_tables": focus,
    }
    write_json(out, ROOT / "reports" / SID / "schema.json")
    return out


def main() -> int:
    out = parse()
    print({k: v for k, v in out.items() if k != "focus_tables"})
    for t, v in out["focus_tables"].items():
        fks = ", ".join(f"{'/'.join(f['columns'])}->{f['references']}" for f in v["fks"])
        cols = [c["name"] for c in v["columns"]]
        print(f"{t}: pk={v['pk']} cols={len(cols)} fks=[{fks}]")
        print("   ", ", ".join(cols))
    return 0


if __name__ == "__main__":
    sys.exit(main())
